name: mydorm
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  blurrycontainer: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.4
  font_awesome_flutter: ^10.6.0
  iconify_flutter: ^0.0.5
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/app-icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "images/dorm-logo.png"

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Sans
      fonts:
        - asset: fonts/Open_Sans/OpenSans-Regular.ttf
        - asset: fonts/Open_Sans/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/Open_Sans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 700